spring:
#  datasource:
#    url: jdbc:mysql://134.175.93.183:3306/database_ynu?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
#    username: qw
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
  #  jpa:
  #    show-sql: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
server:
  port: 8080
swagger:
  enabled: true
  title: "数据库Swagger"
  contact:
    name: "丘武"
    email: "1004901361@qq.com"
  base-package: "com.example.zysx.Controller"
